// 站点与个人信息的集中配置，改这里即可更新首页展示内容。
export const siteConfig = {
  name: 'Static_',
  bio: '一名热爱开源与前端开发的工程师，这里记录我的项目与学习笔记。',
  githubUsername: 'XD-xiao',
  // 个人签名（首页打字机 + 手写下划线效果）
  signature: '保持好奇，保持热爱。',
  // 热力图数据接口，{username} 会自动替换为上面的 githubUsername
  heatmapUrl: 'https://github-contributions-api.jogruber.de/v4/{username}',
  links: {
    github: 'https://github.com/XD-xiao',
    email: '2822334610@qq.com',
    bilibili: 'https://space.bilibili.com/508591743',
  },
  theme: {
    // 是否跟随系统月份自动判定季节；关闭则使用 defaultSeason
    autoSeason: true,
    defaultSeason: 'autumn',
    // 是否启用背景粒子（花瓣/光斑/落叶/飘雪）
    particles: true,
    // 明暗 × 四季 × 时段的主题配色（键名即 CSS 变量名，改这里即可换肤）。
    // 注：背景场景 ThemeBackground.vue 内部的硬编码颜色不在此列。
    colors: {
      // 基础配色（无主题属性时的兜底，如进入页面瞬间）
      base: {
        '--bg': '#f6f8fa',
        '--surface': '#ffffff',
        '--surface-2': '#f6f8fa',
        '--text': '#1f2328',
        '--text-muted': '#59636e',
        '--border': '#d1d9e0',
        '--accent': '#0969da',
        '--overlay-color': 'transparent',
      },
      // 白昼模式：半透明玻璃表面
      light: {
        '--surface': 'rgba(255, 255, 255, 0.72)',
        '--surface-2': 'rgba(255, 255, 255, 0.52)',
        '--border': 'rgba(20, 30, 45, 0.12)',
      },
      // 夜间模式：暗色表面 + 夜空
      dark: {
        '--bg': '#0e1520',
        '--surface': 'rgba(22, 28, 38, 0.66)',
        '--surface-2': 'rgba(30, 38, 50, 0.52)',
        '--text': '#e8eff6',
        '--text-muted': '#9fb0c0',
        '--border': 'rgba(255, 255, 255, 0.14)',
        '--sky-top': '#0a1626',
        '--sky-mid': '#12233a',
        '--sky-horizon': '#1c3348',
        '--scene-silhouette': 'rgba(8, 14, 24, 0.85)',
      },
      // 四季配色（白昼）
      seasons: {
        spring: {
          '--season-primary': '#3e9e6b',
          '--season-secondary': '#8ccb7f',
          '--season-accent': '#f2789f',
          '--season-ground': '#5fae7c',
          '--sky-top': '#9dd3e8',
          '--sky-mid': '#bfe3c8',
          '--sky-horizon': '#e8f0c8',
          '--scene-silhouette': '#4a7a5c',
          '--cloud-top': '#ffffff',
          '--cloud-bottom': '#e3d8ea',
          '--hill-far': '#a4d6a8',
          '--hill-mid': '#7fc48e',
          '--hill-near': '#62b07e',
          '--bloom-1': '#f2789f',
          '--bloom-2': '#ffd166',
          '--bloom-3': '#9ec5ff',
          '--bloom-4': '#ffffff',
          '--tech-line': '#35c2a5',
        },
        summer: {
          '--season-primary': '#d64541',
          '--season-secondary': '#f0a05a',
          '--season-accent': '#ff7a45',
          '--season-ground': '#c0563f',
          '--sky-top': '#5fb0e0',
          '--sky-mid': '#8fd0e8',
          '--sky-horizon': '#ffe0a8',
          '--scene-silhouette': '#5c4a3a',
          '--cloud-top': '#ffffff',
          '--cloud-bottom': '#d5e6f5',
          '--hill-far': '#cfe08a',
          '--hill-mid': '#a9cb60',
          '--hill-near': '#8ab74b',
          '--bloom-1': '#ff7a45',
          '--bloom-2': '#ffd93d',
          '--bloom-3': '#ff5c8a',
          '--bloom-4': '#ffffff',
          '--tech-line': '#2fb0cc',
        },
        autumn: {
          '--season-primary': '#d97a29',
          '--season-secondary': '#e8b45c',
          '--season-accent': '#c0452f',
          '--season-ground': '#b4632a',
          '--sky-top': '#e8c07a',
          '--sky-mid': '#f0c880',
          '--sky-horizon': '#ff9e6b',
          '--scene-silhouette': '#7a5230',
          '--cloud-top': '#fff8ec',
          '--cloud-bottom': '#ecdcc0',
          '--hill-far': '#e0b877',
          '--hill-mid': '#caa055',
          '--hill-near': '#b07d36',
          '--bloom-1': '#c0452f',
          '--bloom-2': '#e8b45c',
          '--bloom-3': '#d97a29',
          '--bloom-4': '#f6e6c8',
          '--tech-line': '#e2a13f',
        },
        winter: {
          '--season-primary': '#6e8ca8',
          '--season-secondary': '#cfe0ec',
          '--season-accent': '#4a7fb5',
          '--season-ground': '#f2f7fb',
          '--sky-top': '#a8c2d8',
          '--sky-mid': '#c4d6e4',
          '--sky-horizon': '#e8f0f6',
          '--scene-silhouette': '#5c7a96',
          '--cloud-top': '#ffffff',
          '--cloud-bottom': '#dfe9f2',
          '--hill-far': '#f0f6fa',
          '--hill-mid': '#dfeaf3',
          '--hill-near': '#c9dceb',
          '--bloom-1': '#8fb8e0',
          '--bloom-2': '#cfe0ec',
          '--bloom-3': '#b0c9e8',
          '--bloom-4': '#ffffff',
          '--tech-line': '#85b9de',
        },
      },
      // 四季配色（夜间，提亮以适配暗色底）
      darkSeasons: {
        spring: {
          '--season-primary': '#55b983',
          '--season-secondary': '#a5d89b',
          '--season-accent': '#f29bb6',
          '--season-ground': '#3e7a58',
          '--hill-far': '#1d3d34',
          '--hill-mid': '#173229',
          '--hill-near': '#11261f',
          '--bloom-1': '#b25f7f',
          '--bloom-2': '#b08f4f',
          '--bloom-3': '#6d86b8',
          '--bloom-4': '#cfd8e2',
          '--tech-line': '#6fdcc0',
        },
        summer: {
          '--season-primary': '#e87a74',
          '--season-secondary': '#f2bc80',
          '--season-accent': '#ff9a70',
          '--season-ground': '#8a4a38',
          '--hill-far': '#2c2f22',
          '--hill-mid': '#25281c',
          '--hill-near': '#1c1f15',
          '--bloom-1': '#a8543a',
          '--bloom-2': '#a8842e',
          '--bloom-3': '#a84a63',
          '--bloom-4': '#cfd8e2',
          '--tech-line': '#6fd0e0',
        },
        autumn: {
          '--season-primary': '#e89a50',
          '--season-secondary': '#efc87e',
          '--season-accent': '#d96852',
          '--season-ground': '#8a5a2e',
          '--hill-far': '#33301f',
          '--hill-mid': '#2a2718',
          '--hill-near': '#201d11',
          '--bloom-1': '#8f3a26',
          '--bloom-2': '#a8802f',
          '--bloom-3': '#8a4d22',
          '--bloom-4': '#c9bda8',
          '--tech-line': '#f2c168',
        },
        winter: {
          '--season-primary': '#93b4ce',
          '--season-secondary': '#dce8f2',
          '--season-accent': '#6fa3ce',
          '--season-ground': '#33465c',
          '--hill-far': '#24344a',
          '--hill-mid': '#1d2a3c',
          '--hill-near': '#16222f',
          '--bloom-1': '#5f80a8',
          '--bloom-2': '#8fa6bd',
          '--bloom-3': '#7a94b5',
          '--bloom-4': '#c8d6e4',
          '--tech-line': '#a8cfe8',
        },
      },
      // 时段配色（色温叠加层与云层色调；非颜色参数仍在 style.css 中）
      periods: {
        dawn: {
          '--overlay-color': 'rgba(255, 168, 120, 0.22)',
          '--cloud-top': '#ffe3cf',
          '--cloud-bottom': '#c99f9a',
        },
        day: {
          '--overlay-color': 'transparent',
        },
        dusk: {
          '--overlay-color': 'rgba(255, 110, 70, 0.28)',
          '--cloud-top': '#ffd0a4',
          '--cloud-bottom': '#d18a72',
        },
        night: {
          '--overlay-color': 'rgba(30, 50, 90, 0.3)',
          '--cloud-top': '#33465e',
          '--cloud-bottom': '#1e2d40',
        },
        late: {
          '--overlay-color': 'rgba(8, 16, 40, 0.42)',
          '--cloud-top': '#26374c',
          '--cloud-bottom': '#182437',
        },
      },
    },
  },
  
}
